services:
  fluxheim-website:
    build:
      context: ..
      dockerfile: container/Dockerfile
    image: fluxheim-website:1.6.28
    container_name: fluxheim-website
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 15s
    ports:
      - "8080:8080"
