version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
    commit-message:
      prefix: "chore"
      include: scope

  - package-ecosystem: docker
    directories:
      - /container
      - /container/observability
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - container
    commit-message:
      prefix: "chore"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore"
      include: scope
