[[locales]]
locale_id = "en-EU"
html_lang = "en"
url_prefix = "en-eu"
display_name = "English (EU)"

[[locales]]
locale_id = "en-GB"
html_lang = "en-GB"
url_prefix = "en-gb"
display_name = "English (UK)"

[[locales]]
locale_id = "en-US"
html_lang = "en-US"
url_prefix = "en-us"
display_name = "English (US)"

[[locales]]
locale_id = "de-DE"
html_lang = "de-DE"
url_prefix = "de"
display_name = "Deutsch"

[[locales]]
locale_id = "fr-FR"
html_lang = "fr-FR"
url_prefix = "fr"
display_name = "Français"

[[locales]]
locale_id = "sv-SE"
html_lang = "sv-SE"
url_prefix = "sv"
display_name = "Svenska"

[[locales]]
locale_id = "nb-NO"
html_lang = "nb-NO"
url_prefix = "no"
display_name = "Norsk"

[[locales]]
locale_id = "nl-NL"
html_lang = "nl-NL"
url_prefix = "nl"
display_name = "Nederlands"

[[locales]]
locale_id = "fi-FI"
html_lang = "fi-FI"
url_prefix = "fi"
display_name = "Suomi"

[[locales]]
locale_id = "is-IS"
html_lang = "is-IS"
url_prefix = "is"
display_name = "Íslenska"

[[locales]]
locale_id = "da-DK"
html_lang = "da-DK"
url_prefix = "da"
display_name = "Dansk"

[[locales]]
locale_id = "es-ES"
html_lang = "es-ES"
url_prefix = "es"
display_name = "Español"

[[locales]]
locale_id = "pt-PT"
html_lang = "pt-PT"
url_prefix = "pt"
display_name = "Português"

[[locales]]
locale_id = "et-EE"
html_lang = "et-EE"
url_prefix = "et"
display_name = "Eesti"

[[locales]]
locale_id = "lv-LV"
html_lang = "lv-LV"
url_prefix = "lv"
display_name = "Latviešu"

[[locales]]
locale_id = "el-GR"
html_lang = "el-GR"
url_prefix = "el"
display_name = "Ελληνικά"

[[locales]]
locale_id = "it-IT"
html_lang = "it-IT"
url_prefix = "it"
display_name = "Italiano"

[[locales]]
locale_id = "lt-LT"
html_lang = "lt-LT"
url_prefix = "lt"
display_name = "Lietuvių"

[[locales]]
locale_id = "hr-HR"
html_lang = "hr-HR"
url_prefix = "hr"
display_name = "Hrvatski"

[[locales]]
locale_id = "cs-CZ"
html_lang = "cs-CZ"
url_prefix = "cs"
display_name = "Čeština"

[[locales]]
locale_id = "bs-BA"
html_lang = "bs-BA"
url_prefix = "bs"
display_name = "Bosanski"

[[locales]]
locale_id = "bg-BG"
html_lang = "bg-BG"
url_prefix = "bg"
display_name = "Български"

[[locales]]
locale_id = "de-CH"
html_lang = "de-CH"
url_prefix = "ch"
display_name = "Deutsch (Schweiz)"

[[locales]]
locale_id = "ro-RO"
html_lang = "ro-RO"
url_prefix = "ro"
display_name = "Română"
