[[locales]]
locale_id = "en-EU"
html_lang = "en"
url_prefix = "en-eu"
display_name = "English (EU)"

[[locales]]
locale_id = "en-GB"
html_lang = "en-GB"
url_prefix = "en-gb"
display_name = "English (UK)"

[[locales]]
locale_id = "en-US"
html_lang = "en-US"
url_prefix = "en-us"
display_name = "English (US)"

[[locales]]
locale_id = "de-DE"
html_lang = "de-DE"
url_prefix = "de"
display_name = "Deutsch"

[[locales]]
locale_id = "fr-FR"
html_lang = "fr-FR"
url_prefix = "fr"
display_name = "Français"

[[locales]]
locale_id = "sv-SE"
html_lang = "sv-SE"
url_prefix = "sv"
display_name = "Svenska"

[[locales]]
locale_id = "nb-NO"
html_lang = "nb-NO"
url_prefix = "no"
display_name = "Norsk"

[[locales]]
locale_id = "nl-NL"
html_lang = "nl-NL"
url_prefix = "nl"
display_name = "Nederlands"

[[locales]]
locale_id = "fi-FI"
html_lang = "fi-FI"
url_prefix = "fi"
display_name = "Suomi"
