project_name = "Fluxheim"
fluxheim_version = "1.7.3"
github_url = "https://github.com/valkyoth/fluxheim"
releases_url = "https://github.com/valkyoth/fluxheim/releases"
license = "EUPL-1.2"
default_locale = "en-EU"
