#!/usr/bin/env sh
set -eu

port="${FLUXHEIM_WEBSITE_PORT:-8080}"
base="http://127.0.0.1:${port}"

cargo +1.96.0 run --quiet &
pid="$!"
trap 'kill "$pid" >/dev/null 2>&1 || true' EXIT

for _ in 1 2 3 4 5 6 7 8 9 10; do
  if curl -fsS "${base}/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

curl -fsS "${base}/" | grep -q "Memory-safe edge server"
curl -fsS "${base}/en-gb/" | grep -q 'html lang="en-GB"'
curl -fsS "${base}/en-us/" | grep -q 'html lang="en-US"'
curl -fsS "${base}/de/" | grep -q "Herunterladen v1.6.30"
curl -fsS "${base}/fr/" | grep -q "Télécharger v1.6.30"
curl -fsS "${base}/de/download" | grep -q "Systemd-Dienst"
curl -fsS "${base}/de/docs" | grep -q "Statisches Website-Hosting"
curl -fsS "${base}/de/docs/configuration" | grep -q "Schlüssel"
curl -fsS "${base}/de/docs/features" | grep -q "Build-Profil-Aliasse"
curl -fsS "${base}/de/docs/tls-acme" | grep -q "ACME-Challenge-Methoden"
curl -fsS "${base}/de/docs/cache" | grep -q "Cache-Operationen"
curl -fsS "${base}/de/docs/observability" | grep -q "Prometheus-Metriken"
curl -fsS "${base}/de/docs/deployment" | grep -q "Checkliste für Produktionsreife"
curl -fsS "${base}/de/docs/advanced" | grep -q "Zero-Retention-Privacy-Modus"
curl -fsS "${base}/de/docs/reference" | grep -q "Betrieb und Deployment"
curl -fsS "${base}/de/docs/source/load-balancer-migration" | grep -q "Bekannte Migrationsgrenzen"
curl -fsS "${base}/de/docs/source/load-balancer-ha" | grep -q "Nichtziele fuer 1.5.3"
curl -fsS "${base}/de/docs/source/build-and-podman" | grep -q "Container-Varianten"
curl -fsS "${base}/de/docs/source/systemd" | grep -q "Sandbox-Overrides"
curl -fsS "${base}/de/docs/source/production-readiness" | grep -q "Operator-Pruefungen"
curl -fsS "${base}/de/docs/source/compression" | grep -q "Datenschutz und Sicherheit"
curl -fsS "${base}/de/docs/source/vhost-config" | grep -q "Vhost-Konfigurationsleitfaden"
curl -fsS "${base}/de/docs/source/config-snapshots" | grep -q "Store-Layout"
curl -fsS "${base}/de/docs/source/supply-chain-security" | grep -q "Aktuelle Kontrollen"
curl -fsS "${base}/de/docs/source/github-setup" | grep -q "Empfohlener sicherer Weg"
curl -fsS "${base}/de/docs/source/geoip" | grep -q "Lokale Datenbanken"
curl -fsS "${base}/de/docs/source/macos-development" | grep -q "Lokale Runtime-Pfade"
curl -fsS "${base}/de/docs/source/logging-architecture" | grep -q "Log-Klassen"
curl -fsS "${base}/de/docs/source/metrics-architecture" | grep -q "Kardinalitätsregeln"
curl -fsS "${base}/de/docs/source/legacy-static-http" | grep -q "HTTP/1.0-Static-Modus"
curl -fsS "${base}/de/docs/source/auth-request" | grep -q "Entscheidungsvertrag"
curl -fsS "${base}/de/docs/source/secure-links" | grep -q "Secure-Link-Claims sollten"
curl -fsS "${base}/de/docs/source/release-checklist" | grep -q "Version und Toolchain"
curl -fsS "${base}/de/docs/source/release-notes-template" | grep -q "Release-Hinweise-Vorlage"
curl -fsS "${base}/de/docs/source/release-runbook" | grep -q "GitHub-Release entwerfen"
curl -fsS "${base}/de/docs/source/compliance-evidence-template" | grep -q "Kandidaten-TOE-Grenze"
curl -fsS "${base}/de/docs/source/runtime-baseline" | grep -q "Release-Nachweise"
curl -fsS "${base}/de/docs/source/cloudflare-origin-support" | grep -q "Origin-CA-Automatisierung"
curl -fsS "${base}/de/docs/source/cache-encryption" | grep -q "Eine minimale OpenBao-Policy"
curl -fsS "${base}/de/docs/source/runtime-parity-fixtures" | grep -q "Runtime-Parity-Fixtures"
curl -fsS "${base}/de/docs/source/pingora-core-patch" | grep -q "Rustls-Listener-Zertifikatresolver"
curl -fsS "${base}/de/docs/source/owasp-top10-2025-baseline" | grep -q "A01 Fehlerhafte Zugriffskontrolle"
curl -fsS "${base}/de/docs/source/extraction-dependency-graph" | grep -q "Abhaengigkeitsrichtung"
curl -fsS "${base}/de/docs/source/modularity-policy" | grep -q "500 Zeilen"
curl -fsS "${base}/de/docs/source/modularity-exceptions" | grep -q "Legacy-Pingora"
curl -fsS "${base}/de/docs/source/fluxheim-ecosystem-idea" | grep -q "Fluxheim integrieren koennen"
curl -fsS "${base}/de/docs/source/runtime-facts-and-policy-proofs" | grep -q "Policy Proof"
curl -fsS "${base}/de/docs/source/perl-cgi-support" | grep -q "Perl-CGI-Unterstuetzung"
curl -fsS "${base}/de/docs/source/wasm-extensibility" | grep -q "WASM-Erweiterbarkeit"
curl -fsS "${base}/de/docs/source/image-filter" | grep -q "Bildfilter"
curl -fsS "${base}/de/docs/source/features" | grep -q "Stabile Core-Features"
curl -fsS "${base}/de/docs/source/common-criteria-roadmap" | grep -q "Definition des Sicherheitsproblems"
curl -fsS "${base}/de/docs/source/gateway-recipes" | grep -q "Gemeinsame Server-Basisline"
curl -fsS "${base}/de/docs/source/crypto-rpc-edge" | grep -q "Warum Ethereum zuerst"
curl -fsS "${base}/de/docs/source/versioning-plan" | grep -q "Release-Leiter"
curl -fsS "${base}/de/docs/source/config-reference" | grep -q "TCP-Stream-Proxy"
curl -fsS "${base}/de/docs/source/opentelemetry-tracing" | grep -q "Designziele"
curl -fsS "${base}/de/docs/source/php-fpm-app-recipes" | grep -q "Unterstuetzte PHP-FPM-Funktionalitaet"
curl -fsS "${base}/de/docs/source/php-runtime-support" | grep -q "Implementierte Feature-Flags"
curl -fsS "${base}/de/docs/source/sentinel-mesh" | grep -q "WireGuard-Transportoptionen"
curl -fsS "${base}/de/docs/source/cache-backends" | grep -q "Bewertung des Memory-Caches"
curl -fsS "${base}/de/docs/source/certificate-renewal" | grep -q "Planung der Erneuerungswarteschlange"
curl -fsS "${base}/de/docs/source/programmable-media-edge" | grep -q "Programmierbarer Media-Edge"
curl -fsS "${base}/de/docs/source/waf-architecture" | grep -q "WAF-Audit-Logs sollten enthalten"
curl -fsS "${base}/de/docs/source/fips" | grep -q "Compliance-Grenze"
curl -fsS "${base}/de/docs/source/zero-retention-privacy-mode" | grep -q "Ehrliche Grenze"
curl -fsS "${base}/fr/docs/getting-started" | grep -q "Votre première configuration"
curl -fsS "${base}/fr/changelog" | grep -q "Publié le 19 juin 2026"
curl -fsS "${base}/fr/docs/tls-acme" | grep -q "Méthodes de challenge ACME"
curl -fsS "${base}/fr/docs/cache" | grep -q "Opérations de cache"
curl -fsS "${base}/fr/docs/observability" | grep -q "Métriques Prometheus"
curl -fsS "${base}/fr/docs/deployment" | grep -q "Checklist de préparation production"
curl -fsS "${base}/fr/docs/advanced" | grep -q "Mode privacy sans rétention"
curl -fsS "${base}/fr/docs/reference" | grep -q "Opérations et déploiement"
curl -fsS "${base}/fr/docs/source/load-balancer-migration" | grep -q "Limites de migration connues"
curl -fsS "${base}/fr/docs/source/load-balancer-ha" | grep -q "Non-objectifs pour 1.5.3"
curl -fsS "${base}/fr/docs/source/build-and-podman" | grep -q "Variantes de conteneurs"
curl -fsS "${base}/fr/docs/source/systemd" | grep -q "Overrides de sandbox"
curl -fsS "${base}/fr/docs/source/production-readiness" | grep -q "Controles operateur"
curl -fsS "${base}/fr/docs/source/compression" | grep -q "Confidentialité et sécurité"
curl -fsS "${base}/fr/docs/source/vhost-config" | grep -q "Guide de configuration vhost"
curl -fsS "${base}/fr/docs/source/config-snapshots" | grep -q "Layout du store"
curl -fsS "${base}/fr/docs/source/supply-chain-security" | grep -q "Controles actuels"
curl -fsS "${base}/fr/docs/source/github-setup" | grep -q "Chemin sur recommande"
curl -fsS "${base}/fr/docs/source/geoip" | grep -q "Bases locales"
curl -fsS "${base}/fr/docs/source/macos-development" | grep -q "Chemins runtime locaux"
curl -fsS "${base}/fr/docs/source/logging-architecture" | grep -q "Classes de logs"
curl -fsS "${base}/fr/docs/source/metrics-architecture" | grep -q "Règles de cardinalité"
curl -fsS "${base}/fr/docs/source/legacy-static-http" | grep -q "Mode statique HTTP/1.0"
curl -fsS "${base}/fr/docs/source/auth-request" | grep -q "Contrat de decision"
curl -fsS "${base}/fr/docs/source/secure-links" | grep -q "Les claims secure-link doivent"
curl -fsS "${base}/fr/docs/source/release-checklist" | grep -q "Version et chaine d'outils"
curl -fsS "${base}/fr/docs/source/release-notes-template" | grep -q "Modele de notes de publication"
curl -fsS "${base}/fr/docs/source/release-runbook" | grep -q "Rediger la publication GitHub"
curl -fsS "${base}/fr/docs/source/compliance-evidence-template" | grep -q "Modele de paquet de preuves de conformite"
curl -fsS "${base}/fr/docs/source/runtime-baseline" | grep -q "Preuves de release"
curl -fsS "${base}/fr/docs/source/cloudflare-origin-support" | grep -q "Automatisation Origin CA"
curl -fsS "${base}/fr/docs/source/cache-encryption" | grep -q "Configuration OpenBao Transit"
curl -fsS "${base}/fr/docs/source/runtime-parity-fixtures" | grep -q "Relation avec la baseline runtime"
curl -fsS "${base}/fr/docs/source/pingora-core-patch" | grep -q "Resolver de certificat du listener rustls"
curl -fsS "${base}/fr/docs/source/owasp-top10-2025-baseline" | grep -q "A01 Controle d'acces casse"
curl -fsS "${base}/fr/docs/source/extraction-dependency-graph" | grep -q "Direction des dependances"
curl -fsS "${base}/fr/docs/source/modularity-policy" | grep -q "500 lignes"
curl -fsS "${base}/fr/docs/source/modularity-exceptions" | grep -q "Exceptions legacy"
curl -fsS "${base}/fr/docs/source/fluxheim-ecosystem-idea" | grep -q "Fluxheim tout en gardant"
curl -fsS "${base}/fr/docs/source/runtime-facts-and-policy-proofs" | grep -q "Runtime Facts et Policy Proofs"
curl -fsS "${base}/fr/docs/source/perl-cgi-support" | grep -q "Prise en charge CGI Perl"
curl -fsS "${base}/fr/docs/source/wasm-extensibility" | grep -q "Extensibilité WASM"
curl -fsS "${base}/fr/docs/source/image-filter" | grep -q "Filtre d'image"
curl -fsS "${base}/fr/docs/source/features" | grep -q "Fonctionnalités core stables"
curl -fsS "${base}/fr/docs/source/common-criteria-roadmap" | grep -q "Definition du probleme de securite"
curl -fsS "${base}/fr/docs/source/gateway-recipes" | grep -q "Baseline serveur partagee"
curl -fsS "${base}/fr/docs/source/crypto-rpc-edge" | grep -q "Pourquoi Ethereum d'abord"
curl -fsS "${base}/fr/docs/source/versioning-plan" | grep -q "Echelle de release"
curl -fsS "${base}/fr/docs/source/config-reference" | grep -q "Proxy de flux TCP"
curl -fsS "${base}/fr/docs/source/opentelemetry-tracing" | grep -q "Objectifs de conception"
curl -fsS "${base}/fr/docs/source/php-fpm-app-recipes" | grep -q "Fonctionnalite PHP-FPM prise en charge"
curl -fsS "${base}/fr/docs/source/php-runtime-support" | grep -q "Fonctionnalité flags implementes"
curl -fsS "${base}/fr/docs/source/sentinel-mesh" | grep -q "Options de transport WireGuard"
curl -fsS "${base}/fr/docs/source/cache-backends" | grep -q "Evaluation du cache memoire"
curl -fsS "${base}/fr/docs/source/certificate-renewal" | grep -q "Planification de la file de renouvellement"
curl -fsS "${base}/fr/docs/source/programmable-media-edge" | grep -q "Media edge programmable"
curl -fsS "${base}/fr/docs/source/waf-architecture" | grep -q "Les logs d'audit WAF doivent inclure"
curl -fsS "${base}/fr/docs/source/fips" | grep -q "Frontiere de compliance"
curl -fsS "${base}/fr/docs/source/zero-retention-privacy-mode" | grep -q "Frontiere honnete"
curl -fsS "${base}/de/conf/fluxheim.toml" | grep -q 'hosts = \["fluxheim.eu"\]'
